# CAPSTONE_PROJECT_2023

###
# group: tags
# @name Get tag by id
GET http://localhost:8080/api/v1/tags/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2RlcmF0b3JAZ21haWwuY29tIiwicm9sZXMiOlsiTU9ERVJBVE9SIl0sImlhdCI6MTY5NzA4Njc0OSwiZXhwIjoxNjk3MTczMTQ5fQ.Sn5FJrlJP492A2mPCF_w4IPDq-BL4rKQhkSIlP5Gdh4

###
# group: tags
# @name Search tag
GET http://localhost:8080/api/v1/tags/search?
    name=
    Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE2OTcwODE2OTUsImV4cCI6MTY5NzE2ODA5NX0.EN7WWteNzjhO5SLPr6F7nReVonD1PUrLepRoOd4cfs8

###
# group: tags
# @name Create a tag
POST http://localhost:8080/api/v1/tags
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2RlcmF0b3JAZ21haWwuY29tIiwicm9sZXMiOlsiTU9ERVJBVE9SIl0sImlhdCI6MTY5NzA4ODAwOCwiZXhwIjoxNjk3MTc0NDA4fQ.vzTCZbWMzKU5IBch0sYVGz3IPp4GFlsgxiDDePQO-8E
Content-Type: application/json

{
  "name": "Lop 1"
}

###
# group: tags
# @name Archive a tag
PUT http://localhost:8080/api/v1/tags/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZ3V5ZW5kYW5nZ2lhbmcuaXRAZ21haWwuY29tIiwicm9sZXMiOlsiUk9MRV9NT0RFUkFUT1IiLCJST0xFX0FETUlOIl0sImlhdCI6MTY5Njk2NTEwMCwiZXhwIjoxNjk3MDUxNTAwfQ.qmkH3Ebj_xY3KjBl9h17IXlPlhYq1aKsCuLr1jdgoFA

###
# group: authentication
# @name login
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "admin",
  "password": "aA12345678"
}

> {%
    // TODO: migrate to HTTP Client Response handler API
    // const { access_token } = pm.response.json();
    // pm.environment.set("token", access_token)
%}

###
# group: authentication
# @name forgot password
POST {{railway}}/auth/forgot-password
Content-Type: application/json

{
  "email": "nguyentienkhoi.it@gmail.com"
}

> {%
    // TODO: you can add here Response handler
%}

###
# group: authentication
# @name submit forgot password
POST {{host}}/auth/submit-forgot-password
Content-Type: application/json

{
  "token": "2ce6612b-fc19-4e8c-9f65-79ec54a6d9ea",
  "newPassword": "aA12345678",
  "confirmationPassword": "aA12345678"
}

> {%
    // TODO: migrate to HTTP Client Response handler API
    // const { accessToken } = pm.response.json();
    // pm.environment.set("token", accessToken)
%}

###
# group: authentication
# @name go to forgot password
GET {{host}}/auth/confirm?
    token=2ce6612b-fc19-4e8c-9f65-79ec54a6d9ea
Content-Type: application/json

{
  "email": "nguyentienkhoi.it@gmail.com"
}

> {%
    // TODO: you can add here Response handler
%}

###
# group: authentication
# @name oauth2
GET {{host}}/auth/oauth2
Content-Type: application/json

{
  "email": "khoi@gmail.com",
  "password": "12345678"
}

###
# group: registration
# @name register
POST {{host}}/register
Content-Type: application/json

{
  "username": "moderator",
  "email": "moderator@gmail.com",
  "password": "aA12345678"
}

###
# group: registration
# @name update-register
PUT {{host}}/register
Content-Type: application/json

{
  "id": 3,
  "firstname": "Gác",
  "lastname": "Cổng",
  "phone": "0348479041",
  "gender": true,
  "school": "Trung học phổ thông Liên Hiêp Quốc",
  "province": "Hà Nôi",
  "district": "Cầu Giấy",
  "village": "Dịch Vọng",
  "dateOfBirth": "2001-02-28",
  "classId": 1
}

###
# group: registration
# @name confirm-token
GET {{host}}/register/confirm?
    token=7a21bf02-2734-4cac-9a8e-f43a53bb77b5

###
# group: resource
# @name get resource detail by id
GET {{railway}}/resource/detail/37
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZWFjaGVyIiwicm9sZXMiOlsiVEVBQ0hFUiJdLCJpYXQiOjE2OTc4MDY5NzcsImV4cCI6MTY5Nzg5MzM3N30.6_bn9STYQbVV0tt0yyJL9QbNTL32CH_q3EhNr_Ja5L4

###
# group: resource
# @name get resource by id
GET {{host}}/resource/35
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZWFjaGVyIiwicm9sZXMiOlsiVEVBQ0hFUiJdLCJpYXQiOjE2OTc2NTE4MzMsImV4cCI6MTY5NzczODIzM30.hmjZtwXYptz0rkeHcaTw4OS6ghrPRPRgkWzycKYxYXs

###
# group: resource
# @name search material
GET {{railway}}/resource/materials?
    classId=1&
    bookSeriesId=1&
    subjectId=1&
    bookVolumeId=2&
    chapterId=3&
    lessonId=4&
    pageIndex=1&
    pageSize=2&
    tabResourceType=IMAGE
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZWFjaGVyIiwicm9sZXMiOlsiVEVBQ0hFUiJdLCJpYXQiOjE2OTc4MDY5NzcsImV4cCI6MTY5Nzg5MzM3N30.6_bn9STYQbVV0tt0yyJL9QbNTL32CH_q3EhNr_Ja5L4

###
# group: resource
# @name search media
POST {{host}}/resource/medias?
    name=null&
    tabResourceType=IMAGE&
    pageIndex=1&
    pageSize=2&
    listTags=1,3,10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aHV5bGluaG1hcnVrbzI3MDlAZ21haWwuY29tIiwicm9sZXMiOlsiVEVBQ0hFUiJdLCJpYXQiOjE2OTcxOTQwMTgsImV4cCI6MTY5NzI4MDQxOH0.h4W7898bw4S8ZwH-e96TFztokNdYAr7kgHXlHEgPnvM

###
# group: resource
# @name upload-resource
POST http://localhost:8080/api/v1/resource
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZWFjaGVyIiwicm9sZXMiOlsiVEVBQ0hFUiJdLCJpYXQiOjE2OTc1OTkzNTksImV4cCI6MTY5NzY4NTc1OX0.3oRlAkHcNL90vqVIdsYKKoQS5MTOsW8V4uSbPNiTdiA
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="/D:/3. FPT_UNIVERSITY/SEMETER 1/CEA201 - Computer Organization and Architecture/Document/Topic 16/CH16_Instruction_Level_Parallelism_and_Superscalar_Processors.pptx"

< /D:/3. FPT_UNIVERSITY/SEMETER 1/CEA201 - Computer Organization and Architecture/Document/Topic 16/CH16_Instruction_Level_Parallelism_and_Superscalar_Processors.pptx
--WebAppBoundary
Content-Disposition: form-data; name="subjectId"

1
--WebAppBoundary
Content-Disposition: form-data; name="LessonId"

2
--WebAppBoundary
Content-Disposition: form-data; name="name"

Số học và phân số
--WebAppBoundary
Content-Disposition: form-data; name="description"

description
--WebAppBoundary
Content-Disposition: form-data; name="visualType"

PUBLIC
--WebAppBoundary
Content-Disposition: form-data; name="tagList"

[6, 3, 8]
--WebAppBoundary

###
# group: resource
# @name download resource
GET {{host}}/user-resource/download/d5edff9d-5bc9-4d5f-ae09-09fff0b3dce6.docx
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZ3V5ZW50aWVua2hvaUBnbWFpbC5jb20iLCJyb2xlcyI6WyJURUFDSEVSIl0sImlhdCI6MTY5NjQzOTIzMSwiZXhwIjoxNjk2NTI1NjMxfQ.kpKYy6F-U_w2PbaCv2Psw0X4jkLJUojFUjco9DAUxGw

###
# group: resource
# @name resource-get
GET http://localhost:8080/api/v1/auth/confirm?
    token=f3cba280-ef81-4065-af6c-bd3819e42fdc

###
# group: user resource
# @name action resource
POST {{host}}/user-resource
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZ3V5ZW50aWVua2hvaUBnbWFpbC5jb20iLCJyb2xlcyI6WyJURUFDSEVSIl0sImlhdCI6MTY5NjM1NzIzNywiZXhwIjoxNjk2NDQzNjM3fQ.ujymlIVK2vILPcqPEgpyg9Df-oCuoCs2a9tjVWHjryQ
Content-Type: application/json

{
  "resourceId": 1,
  "actionType": "UNSAVED"
}

###
# group: comment
# @name create comment
POST {{host}}/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZ3V5ZW50aWVua2hvaUBnbWFpbC5jb20iLCJyb2xlcyI6WyJURUFDSEVSIl0sImlhdCI6MTY5NjMwNzY1MywiZXhwIjoxNjk2Mzk0MDUzfQ.XmRj71xgabsX8V4mvZ21paUzJOFDd1hI85D58izIhGo
Content-Type: application/json

{
  "userId": 1,
  "resourceId": 2,
  "content": "Nội dung này không ổn lắm đâu nha,vãi cứt",
  "commentRootId": 1
}

###
# group: comment
# @name see more comment
GET {{host}}/comment/4/more
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZ3V5ZW50aWVua2hvaUBnbWFpbC5jb20iLCJyb2xlcyI6WyJURUFDSEVSIl0sImlhdCI6MTY5NjM5NTAzOSwiZXhwIjoxNjk2NDgxNDM5fQ.oU5d9TrVZ1LiY06hzGJcV6PELf3GDE5D9xTUqi2Hark

###
# group: report comment
# @name create report comment
POST {{host}}/report-comment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZ3V5ZW50aWVua2hvaUBnbWFpbC5jb20iLCJyb2xlcyI6WyJURUFDSEVSIl0sImlhdCI6MTY5NjMwNzY1MywiZXhwIjoxNjk2Mzk0MDUzfQ.XmRj71xgabsX8V4mvZ21paUzJOFDd1hI85D58izIhGo
Content-Type: application/json

{
  "commentId": 1,
  "message": "Nội dung này",
  "reporterId": 2
}

###
# group: report resource
# @name create report resource
POST {{host}}/report-resource
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZ3V5ZW50aWVua2hvaUBnbWFpbC5jb20iLCJyb2xlcyI6WyJURUFDSEVSIl0sImlhdCI6MTY5NjMwNzY1MywiZXhwIjoxNjk2Mzk0MDUzfQ.XmRj71xgabsX8V4mvZ21paUzJOFDd1hI85D58izIhGo
Content-Type: application/json

{
  "resourceId": 1,
  "message": "Nội dung này",
  "reporterId": 2
}

###
# group: other
# @name other-get
GET {{host}}/auth/test

###
# group: resource tag
# @name Get tags by resource
GET http://localhost:8080/api/v1/resource-tags/class_tbl/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aHV5bGluaG1hcnVrbzI3MDlAZ21haWwuY29tIiwicm9sZXMiOlsiVEVBQ0hFUiJdLCJpYXQiOjE2OTcwOTQ1NjMsImV4cCI6MTY5NzE4MDk2M30.LUY2LMjdmH0wPTWBrcY1HsFaclV2debOgL84Oysf0AA

###
# group: resource tag
# @name Apply tag to a resource
POST http://localhost:8080/api/v1/resource-tags/class_tbl/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2RlcmF0b3JAZ21haWwuY29tIiwicm9sZXMiOlsiTU9ERVJBVE9SIl0sImlhdCI6MTY5NzA4OTk1MCwiZXhwIjoxNjk3MTc2MzUwfQ.0TDccugi_lMogHmWH1OlbwIl0B6c0IsTM_GNZwG5Tz0
Content-Type: application/json

{
  "id": 10,
  "name": "Lop 1"
}

###
# group: resource tag
# @name Disable a tag from resource
PUT http://localhost:8080/api/v1/resource-tags/88
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2RlcmF0b3JAZ21haWwuY29tIiwicm9sZXMiOlsiTU9ERVJBVE9SIl0sImlhdCI6MTY5NzA4OTk1MCwiZXhwIjoxNjk3MTc2MzUwfQ.0TDccugi_lMogHmWH1OlbwIl0B6c0IsTM_GNZwG5Tz0

###
# group: class
# @name create-class
POST http://localhost:8080/api/v1/class
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5NzcyNzE0MywiZXhwIjoxNjk3ODEzNTQzfQ.kh7y6CMujVd-gjx63sPeMPqtD7Ekfn1HMGZFXqKbeqo
Content-Type: application/json

{
  "name": "Class 4"
}

###
# group: class
# @name update-class
PUT http://localhost:8080/api/v1/class/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5NzcyNzE0MywiZXhwIjoxNjk3ODEzNTQzfQ.kh7y6CMujVd-gjx63sPeMPqtD7Ekfn1HMGZFXqKbeqo
Content-Type: application/json

{
  "name": "Class 4"
}

###
# group: class
# @name delete-class
DELETE http://localhost:8080/api/v1/class/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5NzcyNzE0MywiZXhwIjoxNjk3ODEzNTQzfQ.kh7y6CMujVd-gjx63sPeMPqtD7Ekfn1HMGZFXqKbeqo

###
# group: class
# @name view-class
GET http://localhost:8080/api/v1/class/display?
    name=c
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5NzcyNzE0MywiZXhwIjoxNjk3ODEzNTQzfQ.kh7y6CMujVd-gjx63sPeMPqtD7Ekfn1HMGZFXqKbeqo

###
# group: class
# @name get class by id
GET http://localhost:8080/api/v1/class/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5NzcyNzE0MywiZXhwIjoxNjk3ODEzNTQzfQ.kh7y6CMujVd-gjx63sPeMPqtD7Ekfn1HMGZFXqKbeqo

###
# group: book series
# @name create-bookseries
POST http://localhost:8080/api/v1/book-series
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5NzczMTIyNiwiZXhwIjoxNjk3ODE3NjI2fQ.GdvlIdgEIHWLZSooI5TQdOMWG71HZJzkLlY8ZYkC-mI
Content-Type: application/json

{
  "name": "Trí tuệ Việt",
  "classId": 4
}

###
# group: book series
# @name update-bookseries
PUT http://localhost:8080/api/v1/book-series/7
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5NzczMTIyNiwiZXhwIjoxNjk3ODE3NjI2fQ.GdvlIdgEIHWLZSooI5TQdOMWG71HZJzkLlY8ZYkC-mI
Content-Type: application/json

{
  "name": "Trí tuệ Việt Nam",
  "classId": 4
}

###
# group: book series
# @name delete-bookseries
DELETE http://localhost:8080/api/v1/book-series/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5NzczMTIyNiwiZXhwIjoxNjk3ODE3NjI2fQ.GdvlIdgEIHWLZSooI5TQdOMWG71HZJzkLlY8ZYkC-mI

###
# group: book series
# @name view-bookseries
GET http://localhost:8080/api/v1/book-series/display
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5NzczMTIyNiwiZXhwIjoxNjk3ODE3NjI2fQ.GdvlIdgEIHWLZSooI5TQdOMWG71HZJzkLlY8ZYkC-mI

###
# group: book series
# @name get book series by id
GET http://localhost:8080/api/v1/book-series/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5NzczMTIyNiwiZXhwIjoxNjk3ODE3NjI2fQ.GdvlIdgEIHWLZSooI5TQdOMWG71HZJzkLlY8ZYkC-mI

###
# group: subject
# @name create-subject
POST http://localhost:8080/api/v1/subject

###
# group: subject
# @name update-subject
PUT http://localhost:8080/api/v1/subject/

###
# group: subject
# @name delete-subject
DELETE http://localhost:8080/api/v1/subject/

###
# group: subject
# @name view-subject
GET http://localhost:8080/api/v1/subject/display
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5NzczODM4MywiZXhwIjoxNjk3ODI0NzgzfQ.Cp8o8De5GIYc9xWw2hmmq3qiv_Otr0pOLGkzy6qkgB0

###
# group: bookvolume
# @name create-bookvolume
POST http://localhost:8080/api/v1/bookvolume

###
# group: bookvolume
# @name update-bookvolume
PUT http://localhost:8080/api/v1/bookvolume/

###
# group: bookvolume
# @name delete-bookvolume
DELETE http://localhost:8080/api/v1/bookvolume/

###
# group: bookvolume
# @name view-bookvolume
GET http://localhost:8080/api/v1/bookvolume/display

###
# group: chapter
# @name create-chapter
POST http://localhost:8080/api/v1/chapter

###
# group: chapter
# @name update-chapter
PUT http://localhost:8080/api/v1/chapter/

###
# group: chapter
# @name delete-chapter
DELETE http://localhost:8080/api/v1/chapter/

###
# group: chapter
# @name view-chapter
GET http://localhost:8080/api/v1/chapter/display

###
# group: lesson
# @name create-lesson
POST http://localhost:8080/api/v1/lesson

###
# group: lesson
# @name update-lesson
PUT http://localhost:8080/api/v1/lesson/

###
# group: lesson
# @name delete-lesson
DELETE http://localhost:8080/api/v1/lesson/

###
# group: lesson
# @name view-lesson
GET http://localhost:8080/api/v1/lesson/display
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5NzczODM4MywiZXhwIjoxNjk3ODI0NzgzfQ.Cp8o8De5GIYc9xWw2hmmq3qiv_Otr0pOLGkzy6qkgB0

###
# group: moderator-review resource
# @name Approve a resource
POST {{host}}/review/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aHV5bGluaG1hcnVrbzI3MDlAZ21haWwuY29tIiwicm9sZXMiOlsiVEVBQ0hFUiJdLCJpYXQiOjE2OTcwOTcxMzcsImV4cCI6MTY5NzE4MzUzN30.czBIB0RjMCzXuLI48WcWRrK8zK74ebm5jcqrnK24ZlY
Content-Type: application/json

{
  "id": 35,
  "name": "Số tự nhiên ",
  "description": "description",
  "resourceType": "PNG",
  "createdAt": "2023-10-12T11:24:57.937586",
  "active": true,
  "approveType": "UNACCEPTED",
  "visualType": "PUBLIC",
  "thumbnailSrc": "D:/SPRING BOOT LEARNING/backend/resource/56e5ffac-59fa-4118-a8ba-492514296949.png",
  "resourceSrc": "D:/SPRING BOOT LEARNING/backend/resource/56e5ffac-59fa-4118-a8ba-492514296949.png",
  "point": 0,
  "size": 42364,
  "author": {
    "id": 1,
    "firstname": "Sơn",
    "lastname": "Ca",
    "username": "thuylinhmaruko2709@gmail.com",
    "email": "thuylinhmaruko2709@gmail.com",
    "active": true,
    "avatar": "D:/SPRING BOOT LEARNING/backend/resource/resource/default-avatar.jpg",
    "gender": true,
    "dateOfBirth": "2001-09-15",
    "phone": "0355166404",
    "district": "Bình Lục",
    "province": "Hà Nam",
    "school": "Trung học phổ thông B Bình Lục",
    "createdAt": "2023-10-09T21:23:49.176607",
    "violationTime": 0,
    "totalPoint": 10
  }
}

###
# group: moderator-review resource
# @name search for approve-material
GET {{host}}/review/materials?
    name=&
    approveType=null&
    tabResourceType=&
    visualType=&
    pageIndex=1&
    pageSize=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2RlcmF0b3JAZ21haWwuY29tIiwicm9sZXMiOlsiTU9ERVJBVE9SIl0sImlhdCI6MTY5NzUxODM1NCwiZXhwIjoxNjk3NjA0NzU0fQ.La5pTPHBtpdrsTfxR2OtGQHXsXeYSeTjNat6uMKtrY8

###
# group: profile
# @name view profile
GET {{host}}/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "thuylinhmaruko2709@gmail.com",
  "password": "aA12345678"
}

> {%
    // TODO: migrate to HTTP Client Response handler API
    // const { accessToken } = pm.response.json();
    // pm.environment.set("token", accessToken)
%}

###
# group: profile
# @name change avatar
PUT {{host}}/profile/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZWFjaGVyIiwicm9sZXMiOlsiVEVBQ0hFUiJdLCJpYXQiOjE2OTc0MzQ2MTUsImV4cCI6MTY5NzUyMTAxNX0.cj7ryQKY8UgAu0_HfwEqKJnymE33ieXsAxK2nR1RJmM
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="/C:/Users/admin/Pictures/Screenshots/Screenshot 2023-09-15 234421.png"

< /C:/Users/admin/Pictures/Screenshots/Screenshot 2023-09-15 234421.png
--WebAppBoundary

> {%
    // TODO: migrate to HTTP Client Response handler API
    // const { accessToken } = pm.response.json();
    // pm.environment.set("token", accessToken)
%}

###
# group: user
# @name change password
PATCH {{host}}/users/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZWFjaGVyIiwicm9sZXMiOlsiVEVBQ0hFUiJdLCJpYXQiOjE2OTc0MzQ2MTUsImV4cCI6MTY5NzUyMTAxNX0.cj7ryQKY8UgAu0_HfwEqKJnymE33ieXsAxK2nR1RJmM
Content-Type: application/json

{
  "currentPassword": "aA12345678",
  "newPassword": "aA12345678",
  "confirmationPassword": "aA12345678"
}

> {%
    // TODO: migrate to HTTP Client Response handler API
    // const { accessToken } = pm.response.json();
    // pm.environment.set("token", accessToken)
%}

###
# group: user
# @name view user
GET http://localhost:8080/api/v1/users/search?
    name=



###
# group: user
# @name detail user
GET

###
# group: user
# @name reset password user
GET http://localhost:8080/api/v1/users/reset-password

###
# group: user
# @name block user
DELETE http://localhost:8080/api/v1/users/1

###
# group: system permission
# @name get system-permission by id
GET http://localhost:8080/api/v1/system-permission/63
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5Nzc4MTU0NSwiZXhwIjoxNjk3ODY3OTQ1fQ.o9IpyMaIQpRE6oqkp_OlDhtSeEvSXayfPfSX4Ha5c-c

###
# group: system permission
# @name get all system-permission
GET http://localhost:8080/api/v1/system-permission/list
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5Nzg3MjUwNywiZXhwIjoxNjk3OTU4OTA3fQ.rgmrAiAqwv-bIocwY4_jlBxj2NyJ731yTm14l-MG2gk

###
# group: system permission
# @name view search system permission
GET http://localhost:8080/api/v1/system-permission/display?
    name=book&
    pageIndex=1&
    pageSize=9&
    active=true
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5Nzg2MTUwNiwiZXhwIjoxNjk3OTQ3OTA2fQ.yzUYjyiWL0YVcvBAseZAvuHNX8t6k-NQhkJ1ZQQsX0s

###
# group: system permission
# @name change status system-permission
GET http://localhost:8080/api/v1/system-permission/status/65?
    active=true
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5Nzc5NjM4MCwiZXhwIjoxNjk3ODgyNzgwfQ.vVIFv5FMA0zbgDsZMu4gRufdF1lTU3Q1kJne4zBJuNg

###
# group: system permission
# @name create system-permission
POST http://localhost:8080/api/v1/system-permission
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5Nzc5NjM4MCwiZXhwIjoxNjk3ODgyNzgwfQ.vVIFv5FMA0zbgDsZMu4gRufdF1lTU3Q1kJne4zBJuNg
Content-Type: application/json

{
  "permissionName": "a",
  "path": "/api/v1/aaa",
  "methodType": "GET",
  "description": "demo"
}

###
# group: system permission
# @name update system-permission
POST http://localhost:8080/api/v1/system-permission
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5Nzc5NjM4MCwiZXhwIjoxNjk3ODgyNzgwfQ.vVIFv5FMA0zbgDsZMu4gRufdF1lTU3Q1kJne4zBJuNg
Content-Type: application/json

{
  "permissionName": "a",
  "path": "/api/v1/aaa",
  "methodType": "GET",
  "description": "demo"
}

###
# group: role
# @name get role by id
GET http://localhost:8080/api/v1/role/3
Authorization: Bearer {{token}}

###
# group: role
# @name role list search
GET http://localhost:8080/api/v1/role/display?
    name=book&
    pageIndex=1&
    pageSize=9&
    active=true
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5Nzg2MTUwNiwiZXhwIjoxNjk3OTQ3OTA2fQ.yzUYjyiWL0YVcvBAseZAvuHNX8t6k-NQhkJ1ZQQsX0s

###
# group: role
# @name change status role
GET http://localhost:8080/api/v1/role/status/7?
    active=true
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5NzkyNTE4OCwiZXhwIjoxNjk4MDExNTg4fQ.susUJVKYNJBv547zrAgxswq-ACCWLLySwqsH9dnM8XM

###
# group: role
# @name create role
POST http://localhost:8080/api/v1/role
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5Nzg4NDA5NSwiZXhwIjoxNjk3OTcwNDk1fQ.KRcopiLijZxPVBMCikkwrvQ2YeYC8tkYCjq4I_0aWQE
Content-Type: application/json

{
  "roleName": "roleName",
  "description": "roleName"
  // ,"permission": [75, 76]
}

###
# group: role
# @name update role
PUT http://localhost:8080/api/v1/role/7
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTY5NzkxOTg4OSwiZXhwIjoxNjk4MDA2Mjg5fQ.MR2IOVyZoxL2K5SWSSR7h3j5AYDtzuikIsI-boqyLLM
Content-Type: application/json

{
  "roleName": "role update 1",
  "description": "role update 1",
  "permission": [
    10
  ]
}