### Get role by id
GET {{localhost}}/role/3
Authorization: Bearer {{access_token}}
Content-Type: application/json

### Role list search
GET {{localhost}}/role/display?
    name=mo&
    pageIndex=1&
    pageSize=10&
    active=true
Authorization: Bearer {{access_token}}
Content-Type: application/json

### Change status role
GET {{localhost}}/role/status/7?
    active=true
Authorization: Bearer {{access_token}}
Content-Type: application/json

### Create role
POST {{localhost}}/role
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "roleName": "roleName",
  "description": "roleName",
  "permission": [
    75,
    76
  ]
}

### Update role
PUT {{localhost}}/role/7
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "roleName": "role update 1",
  "description": "role update 1",
  "permission": [
    10
  ]
}



